#!/usr/bin/env bash 

# check the existence of config file 
if [ ! -e $HOME/.taskSubmitter_config ] && [ ! -e /.taskSubmitter_config ]; then 
	echo "
            you didn't provide config file, please copy and edit the following lines, 
            then save it to $HOME/.taskSubmitter_config or /.taskSubmitter_config, 
            remember change the permission of the file to 600, so others won't see your password 
            optionally you can use an email dedicatd to sending email 
            
            receiver=PUT_THE_EMAIL_ADDRESS_YOU_WANT_TO_RECEIVE_EMAIL_NOTIFICATION 
            sender=PUT_YOUR_EMAIL_ADDRESS_HERE(it needs to support smtp, currently only support gmail) 
            sender_pass=YOUR PASSWORD 
            sender_name=OPTIONAL
		"	
else 
	nohup $@ > "$(date)" &  
	pid=$!; 
	echo "################# RUN JOB $* ($pid) with email notification ##################"; 
	nohup watcher.py $pid $* 1>/dev/null 2>&1 & 
      echo $(date): \t $(pwd): \t $@ >> $HOME/.submitLog 2>/dev/null 
fi 